"""empty message

Revision ID: 58b580be0e27
Revises: None
Create Date: 2016-11-08 14:31:59.638226

"""

# revision identifiers, used by Alembic.
revision = '58b580be0e27'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akamai_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.Column('stream_id', sa.String(length=80), nullable=False),
    sa.Column('stream_user', sa.String(length=80), nullable=False),
    sa.Column('stream_password', sa.String(length=80), nullable=False),
    sa.Column('primary_url_jinja2_template', sa.String(length=128), nullable=False),
    sa.Column('secondary_url_jinja2_template', sa.String(length=128), nullable=False),
    sa.Column('stream_name_jinja2_template', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_id')
    )
    op.create_table('epiphan_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('primary_pr_vconnector', sa.String(length=16), nullable=False),
    sa.Column('primary_pr_vinput', sa.String(length=16), nullable=False),
    sa.Column('primary_pn_vconnector', sa.String(length=16), nullable=False),
    sa.Column('primary_pn_vinput', sa.String(length=16), nullable=False),
    sa.Column('secondary_pr_vconnector', sa.String(length=16), nullable=False),
    sa.Column('secondary_pr_vinput', sa.String(length=16), nullable=False),
    sa.Column('secondary_pn_vconnector', sa.String(length=16), nullable=False),
    sa.Column('secondary_pn_vinput', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mhcluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('admin_host', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('env', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_host'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('name_id', sa.String(length=128), nullable=False),
    sa.Column('touchscreen_timeout_secs', sa.Integer(), nullable=False),
    sa.Column('touchscreen_allow_recording', sa.Boolean(), nullable=False),
    sa.Column('maintenance_permanent_logs', sa.Boolean(), nullable=False),
    sa.Column('datetime_timezone', sa.String(length=80), nullable=False),
    sa.Column('datetime_ntpserver', sa.String(length=128), nullable=False),
    sa.Column('firmware_version', sa.String(length=80), nullable=False),
    sa.Column('source_deinterlacing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_id')
    )
    op.create_table('ca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('serial_number', sa.String(length=80), nullable=True),
    sa.Column('capture_card_id', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name')
    )
    op.create_table('epiphan_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('channel_id_in_device', sa.Integer(), nullable=False),
    sa.Column('stream_cfg_id', sa.Integer(), nullable=True),
    sa.Column('epiphan_config_id', sa.Integer(), nullable=True),
    sa.Column('audio', sa.Boolean(), nullable=False),
    sa.Column('audiobitrate', sa.Integer(), nullable=False),
    sa.Column('audiochannels', sa.String(length=8), nullable=False),
    sa.Column('audiopreset', sa.String(length=80), nullable=False),
    sa.Column('autoframesize', sa.Boolean(), nullable=False),
    sa.Column('codec', sa.String(length=80), nullable=False),
    sa.Column('fpslimit', sa.Integer(), nullable=False),
    sa.Column('framesize', sa.String(length=80), nullable=False),
    sa.Column('vbitrate', sa.Integer(), nullable=False),
    sa.Column('vencpreset', sa.String(length=8), nullable=False),
    sa.Column('vkeyframeinterval', sa.Integer(), nullable=False),
    sa.Column('vprofile', sa.String(length=8), nullable=False),
    sa.Column('source_layout', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['epiphan_config_id'], ['epiphan_config.id'], ),
    sa.ForeignKeyConstraint(['stream_cfg_id'], ['akamai_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('epiphan_recorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('recorder_id_in_device', sa.Integer(), nullable=False),
    sa.Column('epiphan_config_id', sa.Integer(), nullable=True),
    sa.Column('output_format', sa.String(length=16), nullable=False),
    sa.Column('size_limit_in_kbytes', sa.Integer(), nullable=False),
    sa.Column('time_limit_in_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['epiphan_config_id'], ['epiphan_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mhpearl_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.Column('epiphan_config_id', sa.Integer(), nullable=True),
    sa.Column('mhpearl_version', sa.String(length=80), nullable=False),
    sa.Column('file_search_range_in_sec', sa.Integer(), nullable=False),
    sa.Column('update_frequency_in_sec', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['epiphan_config_id'], ['epiphan_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_recorder_table',
    sa.Column('recorder_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['epiphan_channel.id'], ),
    sa.ForeignKeyConstraint(['recorder_id'], ['epiphan_recorder.id'], )
    )
    op.create_table('role',
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ca_id'], ['ca.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['mhcluster.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['epiphan_config.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('ca_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_table('association_recorder_table')
    op.drop_table('mhpearl_config')
    op.drop_table('epiphan_recorder')
    op.drop_table('epiphan_channel')
    op.drop_table('ca')
    op.drop_table('vendor')
    op.drop_table('mhcluster')
    op.drop_table('location')
    op.drop_table('epiphan_config')
    op.drop_table('akamai_config')
    ### end Alembic commands ###
